apiVersion: v1
kind: Service
metadata:
   name: spring-boot-websocket-chat-demo
   labels:
      app: spring-boot-websocket-chat-demo
spec:
   type: NodePort
   ports:
   - port: 8080
     nodePort: 30001
     protocol: TCP
   selector:
      app: spring-boot-websocket-chat-demo